baseURL = "https://www.kaperd.ml/"
languageCode = "en-us"
title = "Site for game 'Catan'"
theme = "ananke"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]
